### ISSUE TITLE
paint view 内存过大

### ISSUE THREAD

**Issue by unknown92** [lfkdsk/JustWeTools#2]
你好，之前在代码中使用了你的paint view，发现内存消耗很大，尤其是在反复的涂抹、清除、保存等情况下，内存会占用20M以上，研究了一下源码，觉得在处理bitmap的背景、还有bitmap的保存等地方还可以进行优化

**Comment by lfkdsk** [comment]
请问具体是在哪个地方呢？

**Comment by unknown92** [comment]
比如图片保存之后没有将bitmap recycle，还有在paint背景啊还有清除画布的时候有多个地方用到bitmap，猜测大概就是这些地方导致内存没有释放

**Comment by unknown92** [comment]
还有应该不需要使用Bitmap.Config.RGB_8888这么高的质量，我是集成到平板的开发的，存储下来的签名文件基本都在七八百K的大小

**Comment by lfkdsk** [comment]
签名文件？你是指什么？

**Comment by unknown92** [comment]
就是将签名的图片保存下来的jpg文件

**Comment by lfkdsk** [comment]
多谢提醒，你可以单开个分支针对需要修改一下。😘😘😘

**Comment by lfkdsk** [comment]
另外，2.3之后bitmap全放进堆当中了，完全gc托管了，应当不需要.recycle()手动执行了。
