### ISSUE TITLE
绘图是否可以添加压感效果

### ISSUE THREAD

**Issue by tianshaokai** [lfkdsk/JustWeTools#4]
我用手写笔去画图，没有压感的效果，最好还加入绘画各种图形的功能

**Comment by lfkdsk** [comment]
嗯嗯，Demo里有带压感的。

**Comment by lfkdsk** [comment]
Demo里是这样的，压感和图形。

发送自 Outlook Mobile<https://aka.ms/blhgte>



On Tue, Feb 2, 2016 at 12:28 AM -0800, "田绍凯" <notifications@github.com<mailto:notifications@github.com>> wrote:


我用手写笔去画图，没有压感的效果，最好还加入绘画各种图形的功能

―

**Comment by lfkdsk** [comment]
你说手写笔啊，手写笔的压感需要屏幕支持，Android普通手机是没有压感的，所以我的压感是模拟的压感。

发送自 Outlook Mobile<https://aka.ms/blhgte>



On Tue, Feb 2, 2016 at 12:28 AM -0800, "田绍凯" <notifications@github.com<mailto:notifications@github.com>> wrote:


我用手写笔去画图，没有压感的效果，最好还加入绘画各种图形的功能

―

**Comment by tianshaokai** [comment]
我是用的带有手写笔的android pad 没有压感效果，就是用毛笔写字的效果，demo 里实现了吗

**Comment by lfkdsk** [comment]
demo里没有毛笔的效果，Paintview只是简单的canvas应用，毛笔的效果要是想做的话一定会用到openGL，从这个方向出发就能做出来的！

**Comment by tianshaokai** [comment]
作者问一下，opengl 实现毛笔效果，有什么思路吗，像云记，和画世界pro 两个app 实现的效果不错，我现在只是使用canvas 实现效果，但也很不理想
