### ISSUE TITLE
Markdown预览不能换行

### ISSUE THREAD

**Issue by MyateJx** [lfkdsk/JustWeTools#6]
在输入框输入一行文字，回车，再输入下一行，但是Markdown预览中回车被一个空格替换，他们显示在同一行

**Comment by lfkdsk** [comment]
markdown语法中两个空格表示回车

**Comment by lfkdsk** [comment]
markdown语法中两个空格表示回车

**Comment by lfkdsk** [comment]
markdown语法中两个空格表示回车

**Comment by MyateJx** [comment]
@lfkdsk 并没有！现在justWeTools回车就是不能换行，输入两个空格表示回车更是没什么用
